### ISSUE TITLE
Add docker and compose files

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#70]
Adding dockerfiles and making docker images available in the DockerHub would be nice.

Additionally, since it has dependency on IPFS, it would be nice to also provide a docker-compose file to make "one command and ready to rock" experience.

**Comment by machawk1** [comment]
@ibnesayeed I believe a Dockerfile already exists for ipfs. We might use this as the basis.

**Comment by VictorBjelkholm** [comment]
Should be relatively simple to use IPFS with a docker-compose file. One example:

```
version: '2'
services:
  daemon:
    image: ipfs/go-ipfs:v0.4.3-rc2
    volumes:
      - ./ipfs:/data/ipfs
    ports:
      - "4001:4001"
      - "4002:4002"
      - "5001:5001"
      - "8080:8080"
    environment:
      - IPFS_LOGGING=
    restart: always
```

You can also find a list of the tags here: https://hub.docker.com/r/ipfs/go-ipfs/tags/
